// Implementation file for parser generated by fsyacc
module VoletaSharp.Compiler.Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"

open VoletaSharp.Compiler.Syntax

# 10 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | PLUS
  | MINUS
  | TIMES
  | DIVIDEDBY
  | LPAREN
  | RPAREN
  | NUMBER of (int)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_PLUS
    | TOKEN_MINUS
    | TOKEN_TIMES
    | TOKEN_DIVIDEDBY
    | TOKEN_LPAREN
    | TOKEN_RPAREN
    | TOKEN_NUMBER
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_Expr
    | NONTERM_Term
    | NONTERM_Factor

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | PLUS  -> 1 
  | MINUS  -> 2 
  | TIMES  -> 3 
  | DIVIDEDBY  -> 4 
  | LPAREN  -> 5 
  | RPAREN  -> 6 
  | NUMBER _ -> 7 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_PLUS 
  | 2 -> TOKEN_MINUS 
  | 3 -> TOKEN_TIMES 
  | 4 -> TOKEN_DIVIDEDBY 
  | 5 -> TOKEN_LPAREN 
  | 6 -> TOKEN_RPAREN 
  | 7 -> TOKEN_NUMBER 
  | 10 -> TOKEN_end_of_input
  | 8 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_Expr 
    | 3 -> NONTERM_Expr 
    | 4 -> NONTERM_Expr 
    | 5 -> NONTERM_Term 
    | 6 -> NONTERM_Term 
    | 7 -> NONTERM_Term 
    | 8 -> NONTERM_Factor 
    | 9 -> NONTERM_Factor 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 10 
let _fsyacc_tagOfErrorTerminal = 8

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | PLUS  -> "PLUS" 
  | MINUS  -> "MINUS" 
  | TIMES  -> "TIMES" 
  | DIVIDEDBY  -> "DIVIDEDBY" 
  | LPAREN  -> "LPAREN" 
  | RPAREN  -> "RPAREN" 
  | NUMBER _ -> "NUMBER" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | TIMES  -> (null : System.Object) 
  | DIVIDEDBY  -> (null : System.Object) 
  | LPAREN  -> (null : System.Object) 
  | RPAREN  -> (null : System.Object) 
  | NUMBER _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us;65535us;1us;65535us;0us;1us;2us;65535us;0us;2us;16us;4us;4us;65535us;0us;9us;5us;6us;7us;8us;16us;9us;6us;65535us;0us;14us;5us;14us;7us;14us;10us;11us;12us;13us;16us;14us;|]
let _fsyacc_sparseGotoTableRowOffsets = [|0us;1us;3us;6us;11us;|]
let _fsyacc_stateToProdIdxsTableElements = [| 1us;0us;1us;0us;3us;1us;2us;3us;1us;1us;3us;2us;3us;9us;1us;2us;3us;2us;5us;6us;1us;3us;3us;3us;5us;6us;3us;4us;5us;6us;1us;5us;1us;5us;1us;6us;1us;6us;1us;7us;1us;8us;1us;9us;1us;9us;|]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us;2us;4us;8us;10us;14us;16us;20us;22us;26us;30us;32us;34us;36us;38us;40us;42us;44us;|]
let _fsyacc_action_rows = 18
let _fsyacc_actionTableElements = [|2us;32768us;5us;16us;7us;15us;0us;49152us;3us;32768us;0us;3us;1us;5us;2us;7us;0us;16385us;3us;32768us;1us;5us;2us;7us;6us;17us;2us;32768us;5us;16us;7us;15us;2us;16386us;3us;10us;4us;12us;2us;32768us;5us;16us;7us;15us;2us;16387us;3us;10us;4us;12us;2us;16388us;3us;10us;4us;12us;2us;32768us;5us;16us;7us;15us;0us;16389us;2us;32768us;5us;16us;7us;15us;0us;16390us;0us;16391us;0us;16392us;2us;32768us;5us;16us;7us;15us;0us;16393us;|]
let _fsyacc_actionTableRowOffsets = [|0us;3us;4us;8us;9us;13us;16us;19us;22us;25us;28us;31us;32us;35us;36us;37us;38us;41us;|]
let _fsyacc_reductionSymbolCounts = [|1us;2us;3us;3us;1us;3us;3us;1us;1us;3us;|]
let _fsyacc_productionToNonTerminalTable = [|0us;1us;2us;2us;2us;3us;3us;3us;4us;4us;|]
let _fsyacc_immediateActions = [|65535us;49152us;65535us;16385us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;16389us;65535us;16390us;16391us;16392us;65535us;16393us;|]
let _fsyacc_reductions = lazy [|
# 120 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> VoletaSharp.Compiler.Syntax.Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : 'gentype__startstart));
# 129 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 14 "Parser.fsy"
                                       _1 
                   )
# 14 "Parser.fsy"
                 : VoletaSharp.Compiler.Syntax.Expr));
# 140 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_Term in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 17 "Parser.fsy"
                                            AddOp(_1, Plus, _3) 
                   )
# 17 "Parser.fsy"
                 : 'gentype_Expr));
# 152 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_Term in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 18 "Parser.fsy"
                                             AddOp(_1, Minus, _3) 
                   )
# 18 "Parser.fsy"
                 : 'gentype_Expr));
# 164 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Term in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 19 "Parser.fsy"
                                  Term(_1) 
                   )
# 19 "Parser.fsy"
                 : 'gentype_Expr));
# 175 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Term in
            let _3 = parseState.GetInput(3) :?> 'gentype_Factor in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 22 "Parser.fsy"
                                               MulOp(_1, Times, _3) 
                   )
# 22 "Parser.fsy"
                 : 'gentype_Term));
# 187 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Term in
            let _3 = parseState.GetInput(3) :?> 'gentype_Factor in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 23 "Parser.fsy"
                                                   MulOp(_1, DividedBy, _3) 
                   )
# 23 "Parser.fsy"
                 : 'gentype_Term));
# 199 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_Factor in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 24 "Parser.fsy"
                                    Factor(_1) 
                   )
# 24 "Parser.fsy"
                 : 'gentype_Term));
# 210 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> int in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 27 "Parser.fsy"
                                    Digit(_1) 
                   )
# 27 "Parser.fsy"
                 : 'gentype_Factor));
# 221 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 28 "Parser.fsy"
                                                ParenthesisExpression(_2) 
                   )
# 28 "Parser.fsy"
                 : 'gentype_Factor));
|]
# 233 "Parser.fs"
let tables : FSharp.Text.Parsing.Tables<_> = 
  { reductions = _fsyacc_reductions.Value;
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 11;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = tables.Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : VoletaSharp.Compiler.Syntax.Expr =
    engine lexer lexbuf 0 :?> _
