<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GenerateFsl>true</GenerateFsl>
    <GenerateFsy>true</GenerateFsy>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Syntax.fs" />
    <FsYacc Include="Parser.fsy">
      <OtherFlags>--module VoletaSharp.Compiler.Parser</OtherFlags>
    </FsYacc>
    <FsLex Include="Lexer.fsl">
      <OtherFlags>--unicode</OtherFlags>
    </FsLex>
    <Compile Include="Parser.fs" />
    <Compile Include="Lexer.fs" />
    <Compile Include="CodeGen.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsLexYacc" Version="11.3.0" PrivateAssets="all" />
    <PackageReference Include="FsLexYacc.Runtime" Version="11.3.0" />
    <PackageReference Include="LLVMSharp" Version="20.1.2" />
    <PackageReference Include="libLLVM" Version="20.1.2" />
    <PackageReference Include="libLLVM.runtime.win-x64" Version="20.1.2" />
  </ItemGroup>

</Project>
